name: news_api_flutter_package
description: Flutter package for accessing News API. (https://newsapi.org/)
version: 1.2.0
homepage: https://github.com/sharmadhiraj/news_api_flutter_package

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^2.0.0